### ISSUE TITLE
Examples and website

### ISSUE THREAD

**Issue by dkowis** [ActiveRDF/ActiveRDF#1]
This isn't really an issue with the code.

www.activerdf.org doesn't ever respond, and the wiki for the GettingStarted is just the default wiki on github.

Is there a different website, or another source for examples?

Thanks

**Comment by ActiveRDF** [comment]
Thanks for the notification. The server's IP has changed and the nameserver has been updated. The wiki will be transferred to github and updated with the release of the next version.
